"""Domain contracts: interfaces implemented by infrastructure.

Domain and application depend on these; infrastructure provides implementations.
No dependency on infrastructure in this module.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable
from uuid import UUID


@runtime_checkable
class IProjectRepository(Protocol):
    def get(self, project_id: UUID): ...
    def list_all(self): ...
    def add(self, project) -> None: ...


@runtime_checkable
class IDocumentRepository(Protocol):
    def get(self, document_id: UUID): ...
    def list_by_project(self, project_id: UUID): ...
    def add(self, document) -> None: ...


@runtime_checkable
class IPageRepository(Protocol):
    def get(self, page_id: UUID): ...
    def list_by_document(self, document_id: UUID): ...
    def add(self, page) -> None: ...
    def add_many(self, pages: list) -> None: ...


@runtime_checkable
class IOverlayRepository(Protocol):
    def get(self, overlay_id: UUID): ...
    def list_by_page(self, page_id: UUID): ...
    def list_by_project(self, project_id: UUID): ...
    def add(self, overlay) -> None: ...
    def delete(self, overlay_id: UUID) -> None: ...


@runtime_checkable
class IQuantitySnapshotRepository(Protocol):
    def get_latest(self, project_id: UUID): ...
    def add(self, snapshot) -> None: ...


@runtime_checkable
class IExportJobRepository(Protocol):
    def add(self, job) -> None: ...
    def list_by_project(self, project_id: UUID): ...


@runtime_checkable
class IStorageBackend(Protocol):
    """Store and resolve paths for PDFs and page images."""

    def store_pdf(self, document_id: UUID, filename: str, pdf_bytes: bytes) -> str: ...
    def store_page_image(self, document_id: UUID, page_number: int, image_bytes: bytes) -> str: ...
    def uri_to_path(self, uri: str): ...


@runtime_checkable
class IPageClassifier(Protocol):
    """Classify page type and optionally return AI suggestions from text."""

    def classify(self, text_content: str) -> dict: ...


@runtime_checkable
class IPdfExtractor(Protocol):
    """Extract pages from PDF: render images, extract text. Returns list of page data dicts."""

    def extract(self, pdf_bytes: bytes) -> list[dict]: ...
