import type {
  QSProject,
  QSSummary,
  QSFile,
  QSPage,
  QSRoom,
  QSDimension,
  QSNote,
  QSAnnotation,
  QSIssue,
} from "./qsme-types"

// ── Summary helper ──

function computeSummary(files: QSFile[]): QSSummary {
  const allRooms = files.flatMap((f) => f.pages.flatMap((p) => p.rooms))
  const allDims = files.flatMap((f) => f.pages.flatMap((p) => p.dimensions))
  const allNotes = files.flatMap((f) => f.pages.flatMap((p) => p.notes))
  const allAnnotations = files.flatMap((f) => f.pages.flatMap((p) => p.annotations))

  const countType = (t: string) => allRooms.filter((r) => r.type === t).length

  return {
    totalUnits: 1,
    totalRooms: allRooms.length,
    totalBedrooms: countType("bedroom"),
    totalBathrooms: countType("bathroom"),
    totalKitchens: countType("kitchen"),
    totalLivingRooms: countType("living"),
    totalStorageRooms: countType("storage"),
    totalCorridors: countType("corridor"),
    totalUtilityRooms: countType("utility"),
    totalOffices: countType("office"),
    totalReceptions: countType("reception"),
    totalOtherRooms: countType("other"),
    totalArea: allRooms.reduce((sum, r) => sum + r.area, 0),
    totalPerimeter: allRooms.reduce((sum, r) => sum + r.perimeter, 0),
    totalDimensions: allDims.length,
    totalNotes: allNotes.length,
    electricalSockets: 47,
    lightPoints: 32,
    dataPoints: 12,
    waterPoints: 8,
    drainPoints: 6,
    doorCount: 18,
    windowCount: 24,
    totalAnnotations: allAnnotations.length,
    extractionConfidence: 87,
  }
}

// ── Mock Pages for Ground Floor ──

const groundFloorPages: QSPage[] = [
  {
    id: "page-1",
    number: 1,
    name: "Ground Floor Plan",
    imageUrl: "/placeholder.svg",
    tags: ["Floor Plan", "Dimensions"],
    status: "done",
    scale: "1:100",
    confidence: 92,
    rooms: [
      { id: "r1", name: "Reception / Lobby", type: "reception", area: 28.5, perimeter: 22.4, level: "Ground", confidence: 95, sourcePage: 1, verified: true },
      { id: "r2", name: "Living Room", type: "living", area: 42.3, perimeter: 26.8, level: "Ground", confidence: 91, sourcePage: 1, verified: true },
      { id: "r3", name: "Kitchen", type: "kitchen", area: 18.6, perimeter: 17.8, level: "Ground", confidence: 94, sourcePage: 1, verified: false },
      { id: "r4", name: "WC", type: "bathroom", area: 4.2, perimeter: 8.4, level: "Ground", confidence: 88, sourcePage: 1, verified: false },
      { id: "r5", name: "Storage", type: "storage", area: 6.8, perimeter: 10.6, level: "Ground", confidence: 79, sourcePage: 1, verified: false },
      { id: "r6", name: "Corridor", type: "corridor", area: 8.1, perimeter: 14.2, level: "Ground", confidence: 85, sourcePage: 1, verified: false },
    ],
    dimensions: [
      { id: "d1", label: "External Wall North", value: 12.5, units: "m", type: "external", confidence: 96, sourcePage: 1, verified: true, startPoint: { x: 50, y: 50 }, endPoint: { x: 500, y: 50 } },
      { id: "d2", label: "External Wall East", value: 8.2, units: "m", type: "external", confidence: 93, sourcePage: 1, verified: true, startPoint: { x: 500, y: 50 }, endPoint: { x: 500, y: 380 } },
      { id: "d3", label: "Living Room Width", value: 6.4, units: "m", type: "internal", confidence: 90, sourcePage: 1, verified: false, startPoint: { x: 80, y: 120 }, endPoint: { x: 340, y: 120 } },
      { id: "d4", label: "Kitchen Width", value: 4.3, units: "m", type: "internal", confidence: 88, sourcePage: 1, verified: false, startPoint: { x: 350, y: 120 }, endPoint: { x: 490, y: 120 } },
      { id: "d5", label: "Front Door", value: 1.2, units: "m", type: "openings", confidence: 97, sourcePage: 1, verified: true, startPoint: { x: 200, y: 380 }, endPoint: { x: 248, y: 380 } },
      { id: "d6", label: "Window W1", value: 1.8, units: "m", type: "openings", confidence: 85, sourcePage: 1, verified: false, startPoint: { x: 100, y: 50 }, endPoint: { x: 172, y: 50 } },
    ],
    notes: [
      { id: "n1", text: "All internal walls 100mm block", category: "General", confidence: 90, position: { x: 250, y: 200 }, sourcePage: 1 },
      { id: "n2", text: "Floor finish: 600x600 porcelain tile", category: "Finishes", confidence: 85, position: { x: 150, y: 280 }, sourcePage: 1 },
      { id: "n3", text: "Fire door FD30 to kitchen", category: "Doors/Windows", confidence: 92, position: { x: 350, y: 180 }, sourcePage: 1 },
    ],
    annotations: [
      { id: "a1", type: "circle", position: { x: 100, y: 100 }, size: { width: 20, height: 20 }, label: "SP1", description: "Smoke detector", createdBy: "System", createdAt: "2026-03-01T10:00:00Z", sourcePage: 1 },
      { id: "a2", type: "triangle", position: { x: 400, y: 300 }, size: { width: 16, height: 16 }, label: "E1", description: "Electrical panel", createdBy: "System", createdAt: "2026-03-01T10:00:00Z", sourcePage: 1 },
    ],
  },
  {
    id: "page-2",
    number: 2,
    name: "First Floor Plan",
    imageUrl: "/placeholder.svg",
    tags: ["Floor Plan", "Dimensions"],
    status: "done",
    scale: "1:100",
    confidence: 89,
    rooms: [
      { id: "r7", name: "Master Bedroom", type: "bedroom", area: 22.4, perimeter: 19.6, level: "First", confidence: 93, sourcePage: 2, verified: true },
      { id: "r8", name: "Bedroom 2", type: "bedroom", area: 14.8, perimeter: 15.8, level: "First", confidence: 90, sourcePage: 2, verified: false },
      { id: "r9", name: "Bedroom 3", type: "bedroom", area: 12.2, perimeter: 14.4, level: "First", confidence: 87, sourcePage: 2, verified: false },
      { id: "r10", name: "Family Bathroom", type: "bathroom", area: 7.6, perimeter: 11.2, level: "First", confidence: 91, sourcePage: 2, verified: true },
      { id: "r11", name: "En-Suite", type: "bathroom", area: 5.1, perimeter: 9.4, level: "First", confidence: 86, sourcePage: 2, verified: false },
      { id: "r12", name: "Landing", type: "corridor", area: 6.3, perimeter: 12.8, level: "First", confidence: 82, sourcePage: 2, verified: false },
    ],
    dimensions: [
      { id: "d7", label: "Master Bedroom Length", value: 5.6, units: "m", type: "internal", confidence: 91, sourcePage: 2, verified: true, startPoint: { x: 80, y: 100 }, endPoint: { x: 304, y: 100 } },
      { id: "d8", label: "Bedroom 2 Width", value: 3.7, units: "m", type: "internal", confidence: 88, sourcePage: 2, verified: false, startPoint: { x: 340, y: 100 }, endPoint: { x: 488, y: 100 } },
      { id: "d9", label: "Bathroom Width", value: 2.8, units: "m", type: "internal", confidence: 85, sourcePage: 2, verified: false, startPoint: { x: 80, y: 280 }, endPoint: { x: 192, y: 280 } },
    ],
    notes: [
      { id: "n4", text: "Bathroom: waterproof membrane to full height", category: "Finishes", confidence: 88, position: { x: 120, y: 300 }, sourcePage: 2 },
      { id: "n5", text: "All bedrooms: carpet finish", category: "Finishes", confidence: 92, position: { x: 200, y: 150 }, sourcePage: 2 },
    ],
    annotations: [],
  },
  {
    id: "page-3",
    number: 3,
    name: "Electrical Layout",
    imageUrl: "/placeholder.svg",
    tags: ["Electrical"],
    status: "done",
    scale: "1:100",
    confidence: 78,
    rooms: [],
    dimensions: [],
    notes: [
      { id: "n6", text: "Consumer unit in utility cupboard", category: "MEP", confidence: 84, position: { x: 400, y: 350 }, sourcePage: 3 },
      { id: "n7", text: "All circuits RCBO protected", category: "MEP", confidence: 90, position: { x: 250, y: 60 }, sourcePage: 3 },
    ],
    annotations: [
      { id: "a3", type: "circle", position: { x: 120, y: 150 }, size: { width: 12, height: 12 }, label: "S1", description: "Double socket", createdBy: "System", createdAt: "2026-03-01T10:00:00Z", sourcePage: 3 },
      { id: "a4", type: "circle", position: { x: 250, y: 150 }, size: { width: 12, height: 12 }, label: "S2", description: "Double socket", createdBy: "System", createdAt: "2026-03-01T10:00:00Z", sourcePage: 3 },
      { id: "a5", type: "triangle", position: { x: 180, y: 200 }, size: { width: 12, height: 12 }, label: "L1", description: "Pendant light point", createdBy: "System", createdAt: "2026-03-01T10:00:00Z", sourcePage: 3 },
    ],
  },
  {
    id: "page-4",
    number: 4,
    name: "Section A-A",
    imageUrl: "/placeholder.svg",
    tags: ["Section"],
    status: "done",
    scale: "1:50",
    confidence: 84,
    rooms: [],
    dimensions: [
      { id: "d10", label: "Floor to Ceiling GF", value: 2.7, units: "m", type: "internal", confidence: 94, sourcePage: 4, verified: true, startPoint: { x: 100, y: 300 }, endPoint: { x: 100, y: 80 } },
      { id: "d11", label: "Floor to Ceiling FF", value: 2.5, units: "m", type: "internal", confidence: 92, sourcePage: 4, verified: false, startPoint: { x: 100, y: 80 }, endPoint: { x: 100, y: -120 } },
    ],
    notes: [
      { id: "n8", text: "Ridge height 8.4m from FFL", category: "General", confidence: 80, position: { x: 300, y: 50 }, sourcePage: 4 },
    ],
    annotations: [],
  },
  {
    id: "page-5",
    number: 5,
    name: "Notes & Specifications",
    imageUrl: "/placeholder.svg",
    tags: ["Notes"],
    status: "done",
    scale: null,
    confidence: 72,
    rooms: [],
    dimensions: [],
    notes: [
      { id: "n9", text: "All works to comply with Building Regs Part L 2025", category: "General", confidence: 95, position: { x: 50, y: 50 }, sourcePage: 5 },
      { id: "n10", text: "External walls: cavity construction, 100mm PIR insulation", category: "General", confidence: 88, position: { x: 50, y: 100 }, sourcePage: 5 },
      { id: "n11", text: "Windows: double glazed aluminium, U-value 1.4", category: "Doors/Windows", confidence: 91, position: { x: 50, y: 150 }, sourcePage: 5 },
      { id: "n12", text: "Roof: concrete interlocking tiles on 50x25 battens", category: "General", confidence: 86, position: { x: 50, y: 200 }, sourcePage: 5 },
    ],
    annotations: [],
  },
]

// ── Mock File for Project 1 ──

const file1: QSFile = {
  id: "file-1",
  name: "Residential_Plot_42_Drawings.pdf",
  status: "ready",
  pages: groundFloorPages,
  uploadedAt: "2026-02-28T09:00:00Z",
}

const file2: QSFile = {
  id: "file-2",
  name: "Plot_42_Structural.pdf",
  status: "ready",
  pages: [
    {
      id: "page-6",
      number: 1,
      name: "Foundation Plan",
      imageUrl: "/placeholder.svg",
      tags: ["Floor Plan", "Dimensions"],
      status: "done",
      scale: "1:50",
      confidence: 91,
      rooms: [],
      dimensions: [
        { id: "d12", label: "Strip Foundation Width", value: 600, units: "mm", type: "external", confidence: 93, sourcePage: 1, verified: true, startPoint: { x: 80, y: 300 }, endPoint: { x: 320, y: 300 } },
        { id: "d13", label: "Foundation Depth", value: 1000, units: "mm", type: "external", confidence: 90, sourcePage: 1, verified: false, startPoint: { x: 400, y: 80 }, endPoint: { x: 400, y: 340 } },
      ],
      notes: [
        { id: "n13", text: "Min bearing capacity 75 kN/m2", category: "General", confidence: 88, position: { x: 200, y: 200 }, sourcePage: 1 },
      ],
      annotations: [],
    },
    {
      id: "page-7",
      number: 2,
      name: "Beam Schedule",
      imageUrl: "/placeholder.svg",
      tags: ["Notes", "Dimensions"],
      status: "done",
      scale: null,
      confidence: 85,
      rooms: [],
      dimensions: [],
      notes: [
        { id: "n14", text: "Steel beam B1: 254x146x31 UB", category: "General", confidence: 92, position: { x: 100, y: 100 }, sourcePage: 2 },
        { id: "n15", text: "Padstone: 440x215x215 concrete", category: "General", confidence: 87, position: { x: 100, y: 150 }, sourcePage: 2 },
      ],
      annotations: [],
    },
  ],
  uploadedAt: "2026-03-01T11:30:00Z",
}

// ── Mock Issues ──

export const MOCK_ISSUES: QSIssue[] = [
  {
    id: "issue-1",
    type: "low-confidence",
    title: "Low OCR Confidence on Page 5",
    description: "Notes & Specifications page has handwritten annotations that reduced OCR accuracy to 72%.",
    severity: "warning",
    page: 5,
    suggestedFix: "Enable OCR fallback mode",
  },
  {
    id: "issue-2",
    type: "labels-missing",
    title: "Missing Room Labels on Page 1",
    description: "Storage room on ground floor has no label in the drawing. Assigned default name.",
    severity: "warning",
    page: 1,
    suggestedFix: "Add room labels manually",
  },
  {
    id: "issue-3",
    type: "scale-missing",
    title: "No Scale Detected on Page 5",
    description: "Notes page does not contain a detectable scale bar or ratio.",
    severity: "error",
    page: 5,
    suggestedFix: "Set scale manually",
  },
]

// ── Mock Projects ──

const projectFiles1 = [file1, file2]

export const MOCK_PROJECTS: QSProject[] = [
  {
    id: "proj-1",
    name: "Residential Plot 42 - New Build",
    client: "Greenfield Developments Ltd",
    location: "Manchester, UK",
    status: "ready",
    createdAt: "2026-02-25T08:00:00Z",
    updatedAt: "2026-03-02T14:30:00Z",
    files: projectFiles1,
    settings: {
      discipline: "architectural",
      units: "m",
      autoDetectScale: true,
      ocrFallback: true,
      processPerPage: true,
    },
    summary: computeSummary(projectFiles1),
  },
  {
    id: "proj-2",
    name: "Office Conversion - Unit 7B",
    client: "Metro Commercial Properties",
    location: "Birmingham, UK",
    status: "processing",
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-03T09:15:00Z",
    files: [
      {
        id: "file-3",
        name: "Unit_7B_Proposed_Plans.pdf",
        status: "processing",
        pages: [
          {
            id: "page-8",
            number: 1,
            name: "Proposed Ground Floor",
            imageUrl: "/placeholder.svg",
            tags: ["Floor Plan"],
            status: "done",
            scale: "1:100",
            confidence: 88,
            rooms: [
              { id: "r13", name: "Open Plan Office", type: "office", area: 85.2, perimeter: 38.4, level: "Ground", confidence: 90, sourcePage: 1, verified: false },
              { id: "r14", name: "Meeting Room 1", type: "office", area: 18.4, perimeter: 17.2, level: "Ground", confidence: 88, sourcePage: 1, verified: false },
              { id: "r15", name: "Meeting Room 2", type: "office", area: 14.6, perimeter: 15.4, level: "Ground", confidence: 86, sourcePage: 1, verified: false },
              { id: "r16", name: "WC Male", type: "bathroom", area: 8.2, perimeter: 11.8, level: "Ground", confidence: 92, sourcePage: 1, verified: false },
              { id: "r17", name: "WC Female", type: "bathroom", area: 8.2, perimeter: 11.8, level: "Ground", confidence: 92, sourcePage: 1, verified: false },
              { id: "r18", name: "Kitchen / Break", type: "kitchen", area: 12.5, perimeter: 14.6, level: "Ground", confidence: 85, sourcePage: 1, verified: false },
            ],
            dimensions: [],
            notes: [],
            annotations: [],
          },
        ],
        uploadedAt: "2026-03-01T10:30:00Z",
      },
    ],
    settings: {
      discipline: "architectural",
      units: "m",
      autoDetectScale: true,
      ocrFallback: false,
      processPerPage: true,
    },
    summary: {
      totalUnits: 1,
      totalRooms: 6,
      totalBedrooms: 0,
      totalBathrooms: 2,
      totalKitchens: 1,
      totalLivingRooms: 0,
      totalStorageRooms: 0,
      totalCorridors: 0,
      totalUtilityRooms: 0,
      totalOffices: 3,
      totalReceptions: 0,
      totalOtherRooms: 0,
      totalArea: 147.1,
      totalPerimeter: 109.2,
      totalDimensions: 0,
      totalNotes: 0,
      electricalSockets: 34,
      lightPoints: 28,
      dataPoints: 22,
      waterPoints: 4,
      drainPoints: 3,
      doorCount: 12,
      windowCount: 16,
      totalAnnotations: 0,
      extractionConfidence: 88,
    },
  },
  {
    id: "proj-3",
    name: "Warehouse Extension Phase 2",
    client: "Apex Logistics PLC",
    location: "Leeds, UK",
    status: "draft",
    createdAt: "2026-03-03T15:00:00Z",
    updatedAt: "2026-03-03T15:00:00Z",
    files: [],
    settings: {
      discipline: "structural",
      units: "m",
      autoDetectScale: true,
      ocrFallback: true,
      processPerPage: true,
    },
    summary: {
      totalUnits: 0,
      totalRooms: 0,
      totalBedrooms: 0,
      totalBathrooms: 0,
      totalKitchens: 0,
      totalLivingRooms: 0,
      totalStorageRooms: 0,
      totalCorridors: 0,
      totalUtilityRooms: 0,
      totalOffices: 0,
      totalReceptions: 0,
      totalOtherRooms: 0,
      totalArea: 0,
      totalPerimeter: 0,
      totalDimensions: 0,
      totalNotes: 0,
      electricalSockets: 0,
      lightPoints: 0,
      dataPoints: 0,
      waterPoints: 0,
      drainPoints: 0,
      doorCount: 0,
      windowCount: 0,
      totalAnnotations: 0,
      extractionConfidence: 0,
    },
  },
  {
    id: "proj-4",
    name: "School Refurbishment - Block C",
    client: "County Education Authority",
    location: "Bristol, UK",
    status: "error",
    createdAt: "2026-02-20T12:00:00Z",
    updatedAt: "2026-02-22T08:45:00Z",
    files: [
      {
        id: "file-4",
        name: "Block_C_Survey.pdf",
        status: "error",
        pages: [],
        uploadedAt: "2026-02-20T12:10:00Z",
      },
    ],
    settings: {
      discipline: "architectural",
      units: "m",
      autoDetectScale: true,
      ocrFallback: true,
      processPerPage: true,
    },
    summary: {
      totalUnits: 0,
      totalRooms: 0,
      totalBedrooms: 0,
      totalBathrooms: 0,
      totalKitchens: 0,
      totalLivingRooms: 0,
      totalStorageRooms: 0,
      totalCorridors: 0,
      totalUtilityRooms: 0,
      totalOffices: 0,
      totalReceptions: 0,
      totalOtherRooms: 0,
      totalArea: 0,
      totalPerimeter: 0,
      totalDimensions: 0,
      totalNotes: 0,
      electricalSockets: 0,
      lightPoints: 0,
      dataPoints: 0,
      waterPoints: 0,
      drainPoints: 0,
      doorCount: 0,
      windowCount: 0,
      totalAnnotations: 0,
      extractionConfidence: 0,
    },
  },
]

export function getProject(id: string): QSProject | undefined {
  return MOCK_PROJECTS.find((p) => p.id === id)
}
